package schema

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"
)

// RenderProto prints the descriptor as proto2 source for readers and for
// other-language tooling. The Go descriptor stays the source of truth.
func RenderProto(fd *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	b.WriteString("// Code generated by packages/sparkplug/internal/schemagen. DO NOT EDIT.\n")
	b.WriteString("//\n// Sparkplug B payload schema for pravara, written from the payload chapter of\n")
	b.WriteString("// the Eclipse Sparkplug 3.0.0 specification. Wire-compatible with conformant\n")
	b.WriteString("// Sparkplug B implementations (field numbers and types per the specification).\n")
	b.WriteString("// Part of pravara-mes, licensed under the repository LICENSE (AGPL-3.0).\n\n")
	fmt.Fprintf(&b, "syntax = %q;\n\npackage %s;\n\n", fd.GetSyntax(), fd.GetPackage())
	fmt.Fprintf(&b, "option go_package = %q;\n\n", fd.GetOptions().GetGoPackage())
	for _, e := range fd.EnumType {
		fmt.Fprintf(&b, "enum %s {\n", e.GetName())
		for _, v := range e.Value {
			fmt.Fprintf(&b, "  %s = %d;\n", v.GetName(), v.GetNumber())
		}
		b.WriteString("}\n\n")
	}
	for _, m := range fd.MessageType {
		renderMessage(&b, m, fd.GetPackage(), "")
	}
	return b.String()
}

func renderMessage(b *strings.Builder, m *descriptorpb.DescriptorProto, pkg, indent string) {
	fmt.Fprintf(b, "%smessage %s {\n", indent, m.GetName())
	in := indent + "  "
	for _, n := range m.NestedType {
		renderMessage(b, n, pkg, in)
	}
	oneofOpen := int32(-1)
	for _, f := range m.Field {
		if f.OneofIndex != nil {
			if oneofOpen != f.GetOneofIndex() {
				fmt.Fprintf(b, "%soneof %s {\n", in, m.OneofDecl[f.GetOneofIndex()].GetName())
				oneofOpen = f.GetOneofIndex()
			}
			fmt.Fprintf(b, "%s  %s %s = %d;\n", in, typeName(f, pkg), f.GetName(), f.GetNumber())
			continue
		}
		if oneofOpen >= 0 {
			fmt.Fprintf(b, "%s}\n", in)
			oneofOpen = -1
		}
		label := "optional"
		if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
			label = "repeated"
		}
		fmt.Fprintf(b, "%s%s %s %s = %d;\n", in, label, typeName(f, pkg), f.GetName(), f.GetNumber())
	}
	if oneofOpen >= 0 {
		fmt.Fprintf(b, "%s}\n", in)
	}
	for _, r := range m.ExtensionRange {
		end := "max"
		if r.GetEnd() != extMax {
			end = fmt.Sprint(r.GetEnd() - 1)
		}
		fmt.Fprintf(b, "%sextensions %d to %s;\n", in, r.GetStart(), end)
	}
	fmt.Fprintf(b, "%s}\n", indent)
	if indent == "" {
		b.WriteString("\n")
	}
}

func typeName(f *descriptorpb.FieldDescriptorProto, pkg string) string {
	if f.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
		return strings.TrimPrefix(f.GetTypeName(), "."+pkg+".")
	}
	return strings.ToLower(strings.TrimPrefix(f.GetType().String(), "TYPE_"))
}
