apiVersion: v1
kind: ConfigMap
metadata:
  name: pravara-config
  namespace: pravara-mes
  labels:
    app.kubernetes.io/name: pravara-mes
data:
  environment: production
  api_url: "https://mes-api.madfam.io"
  ui_url: "https://mes.madfam.io"
  gateway_url: "wss://mes-api.madfam.io/connection/websocket"
  database_host: "postgres-pravara"
  redis_host: "redis-pravara"
  mqtt_broker: "emqx-pravara"
  centrifugo_host: "centrifugo"
