apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pravara-mes

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - emqx.yaml
  - centrifugo.yaml
  - apps.yaml
  - ml-orchestrator.yaml
  - ingress.yaml
  - observability/
  - security/
  - external-secrets/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pravara-mes
