apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pravara-mes

resources:
- ../base

  # Production-specific patches for higher resources
patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: postgres-pravara
    spec:
      template:
        spec:
          containers:
            - name: postgres
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 2000m
                  memory: 4Gi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-pravara
    spec:
      template:
        spec:
          containers:
            - name: redis
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 1Gi
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emqx-pravara
    spec:
      replicas: 3
      template:
        spec:
          containers:
            - name: emqx
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 2000m
                  memory: 2Gi

configMapGenerator:
- behavior: merge
  literals:
  - environment=production
  name: pravara-config

images:
- name: emqx/emqx
  newTag: "5.4"
- name: postgres
  newTag: 16-alpine
- name: pravara-api
  newName: ghcr.io/madfam-org/pravara-api
  newTag: main-a493297
- name: pravara-ui
  newName: ghcr.io/madfam-org/pravara-ui
  newTag: main-a493297
- name: redis
  newTag: 7-alpine
- name: telemetry-worker
  newName: ghcr.io/madfam-org/telemetry-worker
  newTag: main-a493297
